### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by dorianxonic** [cassidyjames/ephemeral#203]
I tried using Elementary browser since Freya and it always freezes the whole system just by playing a youtube video. Ephemeral has the same behaviour.

**Comment by egemenkus** [comment]
Can you share system information for us?

**Comment by janxkoci** [comment]
Yeah WebKitGTK is not great with video (although wikipedia says that Epiphany should be better than Firefox thanks to using Gstreamer - I personally never seen Epiphany being better than Firefox when it comes to video, the performance is usually rather awful).

So this is what "upstream" means - Ephemeral is also using WebKitGTK rendering engine. And of course Ubuntu packaging removes some dependencies from WebKit, so it is even less capable than elsewhere. So there is that.

The simple fact that you have the same issue in multiple browsers means that it's not an issue with this app, but something else (here WebKit, or - less likely - Ubuntu version of it). So it should be reported upstream - or in this case not, because there are already similar reports of this, e.g. [here](https://bugs.webkit.org/show_bug.cgi?id=205075).
