### ISSUE TITLE
Numeric inputs are rendered huge

### ISSUE THREAD

**Issue by wout** [cassidyjames/ephemeral#237]
Numeric inputs are huge and cause layout issues:

![image](https://user-images.githubusercontent.com/107324/78885611-d2c21e00-7a54-11ea-8464-ec7b93bf19f8.png)

In other browsers they are fine:

![image](https://user-images.githubusercontent.com/107324/78885726-013ff900-7a55-11ea-992a-524612db9688.png)

Example page:

https://www.zwartopwit.be/shop/stickers-zelfklevend/folie-wit-permanent/rechte-hoeken/quality/mono-wit-perm-cmyk

**Comment by cassidyjames** [comment]
This appears to be a combination of issues in WebKitGTK (since it's using the GTK spin button) and the website (since it neither styles nor handles different sizes of number inputs). Since I can reproduce this in the latest GNOME Web (Epiphany) technology preview, it's not unique to Ephemeral, and I can't easily fix it.

![image](https://user-images.githubusercontent.com/611168/78920030-09496a00-7a50-11ea-8c92-8b1b861ad72d.png)
