### ISSUE TITLE
Native PDF viewing

### ISSUE THREAD

**Issue by davidjendreizak** [cassidyjames/ephemeral#94]
Is native PDF viewing possible?

**Comment by TingPing** [comment]
Should probably just bundle [pdf.js](https://mozilla.github.io/pdf.js/).

**Comment by cassidyjames** [comment]
@davidjendreizak I'm not sure if I want to handle it in-app as it's really more of a download use case. PDFs aren't a great experience on the web, anyway, and something like PDF.js will always feel non-native an bolted on.

**Comment by TingPing** [comment]
PDFs are also a major security threat that PDF.js will protect you from and Evince on the host won't.

**Comment by cassidyjames** [comment]
@TingPing under that line of thought. any downloads are a major security threat and all filetypes should be handled in-app. Which is absolutely out of scope. :wink:

**Comment by davidjendreizak** [comment]
Sounds logical to me. So that's a won't fix I guess. Is it okay if I close the issue? @cassidyjames

**Comment by TingPing** [comment]
@cassidyjames Well... kinda yes. Web browsers are theoretically the safest place to render videos, images, and pdfs since media files are a big exploit surface. Browsers also generally make very big scary warnings about downloading executables of any form. Obviously you can't handle anything but its about preventing the easy exploits =)

**Comment by cassidyjames** [comment]
@davidjendreizak I got it. :smile:
